/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Cervo API
 * API for managing bookmarks, workspaces, and members with API key authentication
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetInvitesToken200,
  GetInvitesToken404,
  GetInvitesToken500,
  PostInvitesTokenAccept200,
  PostInvitesTokenAccept400,
  PostInvitesTokenAccept403,
  PostInvitesTokenAccept404,
  PostInvitesTokenAccept422,
  PostInvitesTokenAccept500,
  PostWorkspacesWorkspaceIdInvites201,
  PostWorkspacesWorkspaceIdInvites403,
  PostWorkspacesWorkspaceIdInvites404,
  PostWorkspacesWorkspaceIdInvites500,
  PostWorkspacesWorkspaceIdInvitesBody
} from '../cervoAPI.schemas';

import { apiClient } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Create an invite link for a workspace
 */
export type postWorkspacesWorkspaceIdInvitesResponse201 = {
  data: PostWorkspacesWorkspaceIdInvites201
  status: 201
}

export type postWorkspacesWorkspaceIdInvitesResponse403 = {
  data: PostWorkspacesWorkspaceIdInvites403
  status: 403
}

export type postWorkspacesWorkspaceIdInvitesResponse404 = {
  data: PostWorkspacesWorkspaceIdInvites404
  status: 404
}

export type postWorkspacesWorkspaceIdInvitesResponse500 = {
  data: PostWorkspacesWorkspaceIdInvites500
  status: 500
}

export type postWorkspacesWorkspaceIdInvitesResponseSuccess = (postWorkspacesWorkspaceIdInvitesResponse201) & {
  headers: Headers;
};
export type postWorkspacesWorkspaceIdInvitesResponseError = (postWorkspacesWorkspaceIdInvitesResponse403 | postWorkspacesWorkspaceIdInvitesResponse404 | postWorkspacesWorkspaceIdInvitesResponse500) & {
  headers: Headers;
};

export type postWorkspacesWorkspaceIdInvitesResponse = (postWorkspacesWorkspaceIdInvitesResponseSuccess | postWorkspacesWorkspaceIdInvitesResponseError)

export const getPostWorkspacesWorkspaceIdInvitesUrl = (workspaceId: string,) => {




  return `/api/v1/workspaces/${workspaceId}/invites`
}

export const postWorkspacesWorkspaceIdInvites = async (workspaceId: string,
    postWorkspacesWorkspaceIdInvitesBody: PostWorkspacesWorkspaceIdInvitesBody, options?: RequestInit): Promise<postWorkspacesWorkspaceIdInvitesResponse> => {

  return apiClient<postWorkspacesWorkspaceIdInvitesResponse>(getPostWorkspacesWorkspaceIdInvitesUrl(workspaceId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postWorkspacesWorkspaceIdInvitesBody,)
  }
);}




export const getPostWorkspacesWorkspaceIdInvitesMutationOptions = <TError = PostWorkspacesWorkspaceIdInvites403 | PostWorkspacesWorkspaceIdInvites404 | PostWorkspacesWorkspaceIdInvites500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWorkspacesWorkspaceIdInvites>>, TError,{workspaceId: string;data: PostWorkspacesWorkspaceIdInvitesBody}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postWorkspacesWorkspaceIdInvites>>, TError,{workspaceId: string;data: PostWorkspacesWorkspaceIdInvitesBody}, TContext> => {

const mutationKey = ['postWorkspacesWorkspaceIdInvites'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postWorkspacesWorkspaceIdInvites>>, {workspaceId: string;data: PostWorkspacesWorkspaceIdInvitesBody}> = (props) => {
          const {workspaceId,data} = props ?? {};

          return  postWorkspacesWorkspaceIdInvites(workspaceId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostWorkspacesWorkspaceIdInvitesMutationResult = NonNullable<Awaited<ReturnType<typeof postWorkspacesWorkspaceIdInvites>>>
    export type PostWorkspacesWorkspaceIdInvitesMutationBody = PostWorkspacesWorkspaceIdInvitesBody
    export type PostWorkspacesWorkspaceIdInvitesMutationError = PostWorkspacesWorkspaceIdInvites403 | PostWorkspacesWorkspaceIdInvites404 | PostWorkspacesWorkspaceIdInvites500

    export const usePostWorkspacesWorkspaceIdInvites = <TError = PostWorkspacesWorkspaceIdInvites403 | PostWorkspacesWorkspaceIdInvites404 | PostWorkspacesWorkspaceIdInvites500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWorkspacesWorkspaceIdInvites>>, TError,{workspaceId: string;data: PostWorkspacesWorkspaceIdInvitesBody}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postWorkspacesWorkspaceIdInvites>>,
        TError,
        {workspaceId: string;data: PostWorkspacesWorkspaceIdInvitesBody},
        TContext
      > => {
      return useMutation(getPostWorkspacesWorkspaceIdInvitesMutationOptions(options), queryClient);
    }
    /**
 * Get invite info (public, no auth required)
 */
export type getInvitesTokenResponse200 = {
  data: GetInvitesToken200
  status: 200
}

export type getInvitesTokenResponse404 = {
  data: GetInvitesToken404
  status: 404
}

export type getInvitesTokenResponse500 = {
  data: GetInvitesToken500
  status: 500
}

export type getInvitesTokenResponseSuccess = (getInvitesTokenResponse200) & {
  headers: Headers;
};
export type getInvitesTokenResponseError = (getInvitesTokenResponse404 | getInvitesTokenResponse500) & {
  headers: Headers;
};

export type getInvitesTokenResponse = (getInvitesTokenResponseSuccess | getInvitesTokenResponseError)

export const getGetInvitesTokenUrl = (token: string,) => {




  return `/api/v1/invites/${token}`
}

export const getInvitesToken = async (token: string, options?: RequestInit): Promise<getInvitesTokenResponse> => {

  return apiClient<getInvitesTokenResponse>(getGetInvitesTokenUrl(token),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetInvitesTokenQueryKey = (token: string,) => {
    return [
    `/api/v1/invites/${token}`
    ] as const;
    }


export const getGetInvitesTokenQueryOptions = <TData = Awaited<ReturnType<typeof getInvitesToken>>, TError = GetInvitesToken404 | GetInvitesToken500>(token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvitesToken>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInvitesTokenQueryKey(token);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInvitesToken>>> = ({ signal }) => getInvitesToken(token, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(token), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInvitesToken>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInvitesTokenQueryResult = NonNullable<Awaited<ReturnType<typeof getInvitesToken>>>
export type GetInvitesTokenQueryError = GetInvitesToken404 | GetInvitesToken500


export function useGetInvitesToken<TData = Awaited<ReturnType<typeof getInvitesToken>>, TError = GetInvitesToken404 | GetInvitesToken500>(
 token: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvitesToken>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInvitesToken>>,
          TError,
          Awaited<ReturnType<typeof getInvitesToken>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInvitesToken<TData = Awaited<ReturnType<typeof getInvitesToken>>, TError = GetInvitesToken404 | GetInvitesToken500>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvitesToken>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInvitesToken>>,
          TError,
          Awaited<ReturnType<typeof getInvitesToken>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInvitesToken<TData = Awaited<ReturnType<typeof getInvitesToken>>, TError = GetInvitesToken404 | GetInvitesToken500>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvitesToken>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetInvitesToken<TData = Awaited<ReturnType<typeof getInvitesToken>>, TError = GetInvitesToken404 | GetInvitesToken500>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvitesToken>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetInvitesTokenQueryOptions(token,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Accept an invite and join the workspace
 */
export type postInvitesTokenAcceptResponse200 = {
  data: PostInvitesTokenAccept200
  status: 200
}

export type postInvitesTokenAcceptResponse400 = {
  data: PostInvitesTokenAccept400
  status: 400
}

export type postInvitesTokenAcceptResponse403 = {
  data: PostInvitesTokenAccept403
  status: 403
}

export type postInvitesTokenAcceptResponse404 = {
  data: PostInvitesTokenAccept404
  status: 404
}

export type postInvitesTokenAcceptResponse422 = {
  data: PostInvitesTokenAccept422
  status: 422
}

export type postInvitesTokenAcceptResponse500 = {
  data: PostInvitesTokenAccept500
  status: 500
}

export type postInvitesTokenAcceptResponseSuccess = (postInvitesTokenAcceptResponse200) & {
  headers: Headers;
};
export type postInvitesTokenAcceptResponseError = (postInvitesTokenAcceptResponse400 | postInvitesTokenAcceptResponse403 | postInvitesTokenAcceptResponse404 | postInvitesTokenAcceptResponse422 | postInvitesTokenAcceptResponse500) & {
  headers: Headers;
};

export type postInvitesTokenAcceptResponse = (postInvitesTokenAcceptResponseSuccess | postInvitesTokenAcceptResponseError)

export const getPostInvitesTokenAcceptUrl = (token: string,) => {




  return `/api/v1/invites/${token}/accept`
}

export const postInvitesTokenAccept = async (token: string, options?: RequestInit): Promise<postInvitesTokenAcceptResponse> => {

  return apiClient<postInvitesTokenAcceptResponse>(getPostInvitesTokenAcceptUrl(token),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostInvitesTokenAcceptMutationOptions = <TError = PostInvitesTokenAccept400 | PostInvitesTokenAccept403 | PostInvitesTokenAccept404 | PostInvitesTokenAccept422 | PostInvitesTokenAccept500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInvitesTokenAccept>>, TError,{token: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postInvitesTokenAccept>>, TError,{token: string}, TContext> => {

const mutationKey = ['postInvitesTokenAccept'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postInvitesTokenAccept>>, {token: string}> = (props) => {
          const {token} = props ?? {};

          return  postInvitesTokenAccept(token,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostInvitesTokenAcceptMutationResult = NonNullable<Awaited<ReturnType<typeof postInvitesTokenAccept>>>

    export type PostInvitesTokenAcceptMutationError = PostInvitesTokenAccept400 | PostInvitesTokenAccept403 | PostInvitesTokenAccept404 | PostInvitesTokenAccept422 | PostInvitesTokenAccept500

    export const usePostInvitesTokenAccept = <TError = PostInvitesTokenAccept400 | PostInvitesTokenAccept403 | PostInvitesTokenAccept404 | PostInvitesTokenAccept422 | PostInvitesTokenAccept500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInvitesTokenAccept>>, TError,{token: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postInvitesTokenAccept>>,
        TError,
        {token: string},
        TContext
      > => {
      return useMutation(getPostInvitesTokenAcceptMutationOptions(options), queryClient);
    }
