/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Cervo API
 * API for managing bookmarks, workspaces, and members with API key authentication
 * OpenAPI spec version: 1.0.0
 */
export type GetHealth200Message = typeof GetHealth200Message[keyof typeof GetHealth200Message];


export const GetHealth200Message = {
  ok: 'ok',
} as const;

export type GetHealth200 = {
  message: GetHealth200Message;
};

export type PostBookmarksBodySource = typeof PostBookmarksBodySource[keyof typeof PostBookmarksBodySource];


export const PostBookmarksBodySource = {
  web: 'web',
  discord: 'discord',
  raycast: 'raycast',
  api: 'api',
} as const;

export type PostBookmarksBody = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workspaceId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  memberId: string;
  url: string;
  source?: PostBookmarksBodySource;
};

/**
 * Bookmark submitted for processing
 */
export type PostBookmarks201 = {
  id: string;
  status: string;
};

/**
 * Failed to create bookmark
 */
export type PostBookmarks400 = {
  message: string;
};

/**
 * Workspace or member not found
 */
export type PostBookmarks404 = {
  message: string;
};

/**
 * Failed to create bookmark
 */
export type PostBookmarks500 = {
  message: string;
};

export type GetBookmarksParams = {
/**
 * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
 */
workspaceId: string;
/**
 * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
 */
memberId: string;
/**
 * @minLength 1
 */
text: string;
/**
 * @minimum 1
 * @maximum 50
 */
limit?: number;
};

export type GetBookmarks200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workspaceId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  memberId: string;
  url: string;
  /**
     * @minLength 64
     * @maxLength 64
     */
  urlHashId: string;
  status: string;
  /** @nullable */
  title: string | null;
  /** @nullable */
  description: string | null;
  /** @nullable */
  tags: string[] | null;
  /** @nullable */
  failureReason: string | null;
  source: string;
  createdAt: string;
  updatedAt: string;
  visible: boolean;
  matchedBecause?: string;
};

/**
 * Failed to get bookmarks
 */
export type GetBookmarks400 = {
  message: string;
};

/**
 * Failed to get bookmarks
 */
export type GetBookmarks500 = {
  message: string;
};

/**
 * Retry triggered
 */
export type PostBookmarksIdRetry200 = {
  message: string;
};

/**
 * Bookmark not found
 */
export type PostBookmarksIdRetry404 = {
  message: string;
};

/**
 * Bookmark not in failed state
 */
export type PostBookmarksIdRetry409 = {
  message: string;
};

export type DeleteBookmarksId200 = {
  message: string;
};

export type DeleteBookmarksId404 = {
  message: string;
};

/**
 * Bookmark retrieved successfully
 */
export type GetBookmarksId200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workspaceId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  memberId: string;
  url: string;
  /**
     * @minLength 64
     * @maxLength 64
     */
  urlHashId: string;
  status: string;
  /** @nullable */
  title: string | null;
  /** @nullable */
  description: string | null;
  /** @nullable */
  tags: string[] | null;
  /** @nullable */
  failureReason: string | null;
  source: string;
  createdAt: string;
  updatedAt: string;
  visible: boolean;
};

/**
 * Bookmark not found
 */
export type GetBookmarksId404 = {
  message: string;
};

export type PostWorkspacesCreateBody = {
  /** @minLength 1 */
  name: string;
  description?: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  ownerId: string;
};

export type PostWorkspacesCreate201Workspace = {
  id: string;
  ownerId: string;
  name: string;
  /** @nullable */
  description: string | null;
  isPublic: boolean;
  createdAt: string;
  updatedAt: string;
  active: boolean;
};

/**
 * Workspace created.
 */
export type PostWorkspacesCreate201 = {
  workspace: PostWorkspacesCreate201Workspace;
};

/**
 * Failed to create workspace
 */
export type PostWorkspacesCreate400 = {
  message: string;
};

/**
 * Cannot create workspace due constraint
 */
export type PostWorkspacesCreate422 = {
  message: string;
};

/**
 * Failed to create workspace
 */
export type PostWorkspacesCreate500 = {
  message: string;
};

export type GetWorkspacesParams = {
/**
 * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
 */
id: string;
};

export type GetWorkspaces200Workspace = {
  id: string;
  ownerId: string;
  name: string;
  /** @nullable */
  description: string | null;
  isPublic: boolean;
  createdAt: string;
  updatedAt: string;
  active: boolean;
};

/**
 * Workspace found.
 */
export type GetWorkspaces200 = {
  workspace: GetWorkspaces200Workspace;
};

/**
 * Workspace not found
 */
export type GetWorkspaces404 = {
  message: string;
};

/**
 * Failed to get workspace
 */
export type GetWorkspaces500 = {
  message: string;
};

export type GetWorkspacesMe200WorkspacesItemRole = typeof GetWorkspacesMe200WorkspacesItemRole[keyof typeof GetWorkspacesMe200WorkspacesItemRole];


export const GetWorkspacesMe200WorkspacesItemRole = {
  viewer: 'viewer',
  editor: 'editor',
  owner: 'owner',
} as const;

export type GetWorkspacesMe200WorkspacesItem = {
  id: string;
  /** @nullable */
  ownerId: string | null;
  name: string;
  /** @nullable */
  description: string | null;
  isPublic: boolean;
  isPersonal: boolean;
  createdAt: string;
  updatedAt: string;
  active: boolean;
  role: GetWorkspacesMe200WorkspacesItemRole;
};

/**
 * List of workspaces the member belongs to
 */
export type GetWorkspacesMe200 = {
  workspaces: GetWorkspacesMe200WorkspacesItem[];
};

/**
 * Failed to get workspaces
 */
export type GetWorkspacesMe500 = {
  message: string;
};

export type PatchWorkspacesWorkspaceIdBody = {
  /** @minLength 1 */
  name?: string;
  /** @nullable */
  description?: string | null;
  isPublic?: boolean;
};

export type PatchWorkspacesWorkspaceId200Workspace = {
  id: string;
  /** @nullable */
  ownerId: string | null;
  name: string;
  /** @nullable */
  description: string | null;
  isPublic: boolean;
  isPersonal: boolean;
  createdAt: string;
  updatedAt: string;
  active: boolean;
};

/**
 * Workspace updated
 */
export type PatchWorkspacesWorkspaceId200 = {
  workspace: PatchWorkspacesWorkspaceId200Workspace;
};

/**
 * Bad request
 */
export type PatchWorkspacesWorkspaceId400 = {
  message: string;
};

/**
 * Forbidden
 */
export type PatchWorkspacesWorkspaceId403 = {
  message: string;
};

/**
 * Workspace not found
 */
export type PatchWorkspacesWorkspaceId404 = {
  message: string;
};

/**
 * Internal error
 */
export type PatchWorkspacesWorkspaceId500 = {
  message: string;
};

/**
 * Forbidden
 */
export type DeleteWorkspacesWorkspaceId403 = {
  message: string;
};

/**
 * Workspace not found
 */
export type DeleteWorkspacesWorkspaceId404 = {
  message: string;
};

/**
 * Internal error
 */
export type DeleteWorkspacesWorkspaceId500 = {
  message: string;
};

export type GetWorkspacesWorkspaceIdMembers200MembersItemRole = typeof GetWorkspacesWorkspaceIdMembers200MembersItemRole[keyof typeof GetWorkspacesWorkspaceIdMembers200MembersItemRole];


export const GetWorkspacesWorkspaceIdMembers200MembersItemRole = {
  viewer: 'viewer',
  editor: 'editor',
  owner: 'owner',
} as const;

export type GetWorkspacesWorkspaceIdMembers200MembersItem = {
  id: string;
  /** @nullable */
  name: string | null;
  /** @nullable */
  username: string | null;
  /** @nullable */
  email: string | null;
  role: GetWorkspacesWorkspaceIdMembers200MembersItemRole;
  joinedAt: string;
};

/**
 * List of workspace members
 */
export type GetWorkspacesWorkspaceIdMembers200 = {
  members: GetWorkspacesWorkspaceIdMembers200MembersItem[];
};

/**
 * Forbidden
 */
export type GetWorkspacesWorkspaceIdMembers403 = {
  message: string;
};

/**
 * Internal error
 */
export type GetWorkspacesWorkspaceIdMembers500 = {
  message: string;
};

export type PostWorkspacesWorkspaceIdMembersBodyRole = typeof PostWorkspacesWorkspaceIdMembersBodyRole[keyof typeof PostWorkspacesWorkspaceIdMembersBodyRole];


export const PostWorkspacesWorkspaceIdMembersBodyRole = {
  viewer: 'viewer',
  editor: 'editor',
} as const;

export type PostWorkspacesWorkspaceIdMembersBody = {
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  role?: PostWorkspacesWorkspaceIdMembersBodyRole;
};

/**
 * Member invited
 */
export type PostWorkspacesWorkspaceIdMembers201 = {
  message: string;
};

/**
 * Forbidden
 */
export type PostWorkspacesWorkspaceIdMembers403 = {
  message: string;
};

/**
 * Workspace or member not found
 */
export type PostWorkspacesWorkspaceIdMembers404 = {
  message: string;
};

/**
 * Member already in workspace
 */
export type PostWorkspacesWorkspaceIdMembers422 = {
  message: string;
};

/**
 * Internal error
 */
export type PostWorkspacesWorkspaceIdMembers500 = {
  message: string;
};

/**
 * Member removed
 */
export type DeleteWorkspacesWorkspaceIdMembersMemberId200 = {
  message: string;
};

/**
 * Forbidden
 */
export type DeleteWorkspacesWorkspaceIdMembersMemberId403 = {
  message: string;
};

/**
 * Membership not found
 */
export type DeleteWorkspacesWorkspaceIdMembersMemberId404 = {
  message: string;
};

/**
 * Internal error
 */
export type DeleteWorkspacesWorkspaceIdMembersMemberId500 = {
  message: string;
};

export type PatchWorkspacesWorkspaceIdMembersMemberIdBodyRole = typeof PatchWorkspacesWorkspaceIdMembersMemberIdBodyRole[keyof typeof PatchWorkspacesWorkspaceIdMembersMemberIdBodyRole];


export const PatchWorkspacesWorkspaceIdMembersMemberIdBodyRole = {
  viewer: 'viewer',
  editor: 'editor',
  owner: 'owner',
} as const;

export type PatchWorkspacesWorkspaceIdMembersMemberIdBody = {
  role: PatchWorkspacesWorkspaceIdMembersMemberIdBodyRole;
};

/**
 * Role updated
 */
export type PatchWorkspacesWorkspaceIdMembersMemberId200 = {
  message: string;
};

/**
 * Forbidden
 */
export type PatchWorkspacesWorkspaceIdMembersMemberId403 = {
  message: string;
};

/**
 * Membership not found
 */
export type PatchWorkspacesWorkspaceIdMembersMemberId404 = {
  message: string;
};

/**
 * Internal error
 */
export type PatchWorkspacesWorkspaceIdMembersMemberId500 = {
  message: string;
};

export type PostWorkspacesWorkspaceIdInvitesBodyRole = typeof PostWorkspacesWorkspaceIdInvitesBodyRole[keyof typeof PostWorkspacesWorkspaceIdInvitesBodyRole];


export const PostWorkspacesWorkspaceIdInvitesBodyRole = {
  viewer: 'viewer',
  editor: 'editor',
} as const;

export type PostWorkspacesWorkspaceIdInvitesBody = {
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  role?: PostWorkspacesWorkspaceIdInvitesBodyRole;
  /**
     * @minimum 1
     * @maximum 30
     */
  expiresInDays?: number;
};

/**
 * Invite created
 */
export type PostWorkspacesWorkspaceIdInvites201 = {
  token: string;
  inviteUrl: string;
  expiresAt: string;
};

/**
 * Forbidden
 */
export type PostWorkspacesWorkspaceIdInvites403 = {
  message: string;
};

/**
 * Workspace not found
 */
export type PostWorkspacesWorkspaceIdInvites404 = {
  message: string;
};

/**
 * Internal error
 */
export type PostWorkspacesWorkspaceIdInvites500 = {
  message: string;
};

export type GetWorkspacesWorkspaceIdIntegrations200IntegrationsItem = {
  id: string;
  workspaceId: string;
  provider: string;
  providerId: string;
  /** @nullable */
  providerName: string | null;
  createdAt: string;
  updatedAt: string;
  active: boolean;
};

/**
 * Integrations found
 */
export type GetWorkspacesWorkspaceIdIntegrations200 = {
  integrations: GetWorkspacesWorkspaceIdIntegrations200IntegrationsItem[];
};

/**
 * Forbidden
 */
export type GetWorkspacesWorkspaceIdIntegrations403 = {
  message: string;
};

/**
 * Workspace not found
 */
export type GetWorkspacesWorkspaceIdIntegrations404 = {
  message: string;
};

export type PostWorkspacesWorkspaceIdIntegrationsBody = {
  /** @minLength 1 */
  provider: string;
  /** @minLength 1 */
  providerId: string;
  providerName?: string;
};

export type PostWorkspacesWorkspaceIdIntegrations201Integration = {
  id: string;
  workspaceId: string;
  provider: string;
  providerId: string;
  /** @nullable */
  providerName: string | null;
  createdAt: string;
  updatedAt: string;
  active: boolean;
};

/**
 * Integration added
 */
export type PostWorkspacesWorkspaceIdIntegrations201 = {
  integration: PostWorkspacesWorkspaceIdIntegrations201Integration;
};

/**
 * Forbidden
 */
export type PostWorkspacesWorkspaceIdIntegrations403 = {
  message: string;
};

/**
 * Workspace not found
 */
export type PostWorkspacesWorkspaceIdIntegrations404 = {
  message: string;
};

/**
 * Integration already exists
 */
export type PostWorkspacesWorkspaceIdIntegrations422 = {
  message: string;
};

/**
 * Forbidden
 */
export type DeleteWorkspacesWorkspaceIdIntegrationsIntegrationId403 = {
  message: string;
};

/**
 * Integration not found
 */
export type DeleteWorkspacesWorkspaceIdIntegrationsIntegrationId404 = {
  message: string;
};

export type GetMembersMe200Member = {
  id: string;
  /** @nullable */
  name: string | null;
  /** @nullable */
  username: string | null;
  /** @nullable */
  email: string | null;
  createdAt: string;
  updatedAt: string;
  active: boolean;
};

/**
 * @nullable
 */
export type GetMembersMe200Workspace = {
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  isPublic: boolean;
  createdAt: string;
  updatedAt: string;
  active: boolean;
} | null;

/**
 * Current member
 */
export type GetMembersMe200 = {
  member: GetMembersMe200Member;
  /** @nullable */
  workspace: GetMembersMe200Workspace;
};

/**
 * Unauthorized
 */
export type GetMembersMe401 = {
  message: string;
};

export type PostMembersSync200Member = {
  id: string;
  /** @nullable */
  name: string | null;
  /** @nullable */
  username: string | null;
  /** @nullable */
  email: string | null;
  createdAt: string;
  updatedAt: string;
  active: boolean;
};

/**
 * Member already exists
 */
export type PostMembersSync200 = {
  member: PostMembersSync200Member;
};

export type PostMembersSync201Member = {
  id: string;
  /** @nullable */
  name: string | null;
  /** @nullable */
  username: string | null;
  /** @nullable */
  email: string | null;
  createdAt: string;
  updatedAt: string;
  active: boolean;
};

/**
 * Member created
 */
export type PostMembersSync201 = {
  member: PostMembersSync201Member;
};

/**
 * Unauthorized
 */
export type PostMembersSync401 = {
  message: string;
};

/**
 * Member already exists with different userId
 */
export type PostMembersSync422 = {
  message: string;
};

/**
 * Failed to sync member
 */
export type PostMembersSync500 = {
  message: string;
};

export type PostMembersMeIdentitiesBody = {
  /** @minLength 1 */
  provider: string;
  /** @minLength 1 */
  providerUserId: string;
};

export type PostMembersMeIdentities201Identity = {
  id: string;
  memberId: string;
  provider: string;
  providerUserId: string;
  createdAt: string;
};

/**
 * Identity linked
 */
export type PostMembersMeIdentities201 = {
  identity: PostMembersMeIdentities201Identity;
};

/**
 * Identity already linked to this account
 */
export type PostMembersMeIdentities409 = {
  message: string;
};

/**
 * Identity linked to a different account
 */
export type PostMembersMeIdentities422 = {
  message: string;
};

/**
 * Failed to link identity
 */
export type PostMembersMeIdentities500 = {
  message: string;
};

export type GetMembersMeIdentities200IdentitiesItem = {
  id: string;
  memberId: string;
  provider: string;
  providerUserId: string;
  createdAt: string;
};

/**
 * Member identities
 */
export type GetMembersMeIdentities200 = {
  identities: GetMembersMeIdentities200IdentitiesItem[];
};

/**
 * Invite info
 */
export type GetInvitesToken200 = {
  workspaceName: string;
  /** @nullable */
  inviterName: string | null;
  role: string;
  expiresAt: string;
  expired: boolean;
};

/**
 * Invite not found
 */
export type GetInvitesToken404 = {
  message: string;
};

/**
 * Internal error
 */
export type GetInvitesToken500 = {
  message: string;
};

/**
 * Invite accepted
 */
export type PostInvitesTokenAccept200 = {
  workspaceId: string;
  role: string;
};

/**
 * Invite expired or already used
 */
export type PostInvitesTokenAccept400 = {
  message: string;
};

/**
 * Email mismatch or forbidden
 */
export type PostInvitesTokenAccept403 = {
  message: string;
};

/**
 * Invite not found
 */
export type PostInvitesTokenAccept404 = {
  message: string;
};

/**
 * Already a member of this workspace
 */
export type PostInvitesTokenAccept422 = {
  message: string;
};

/**
 * Internal error
 */
export type PostInvitesTokenAccept500 = {
  message: string;
};

