/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Cervo API
 * API for managing bookmarks, workspaces, and members with API key authentication
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetMembersMe200,
  GetMembersMe401,
  GetMembersMeIdentities200,
  PostMembersMeIdentities201,
  PostMembersMeIdentities409,
  PostMembersMeIdentities422,
  PostMembersMeIdentities500,
  PostMembersMeIdentitiesBody,
  PostMembersSync200,
  PostMembersSync201,
  PostMembersSync401,
  PostMembersSync422,
  PostMembersSync500
} from '../cervoAPI.schemas';

import { apiClient } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get the currently authenticated member
 */
export type getMembersMeResponse200 = {
  data: GetMembersMe200
  status: 200
}

export type getMembersMeResponse401 = {
  data: GetMembersMe401
  status: 401
}

export type getMembersMeResponseSuccess = (getMembersMeResponse200) & {
  headers: Headers;
};
export type getMembersMeResponseError = (getMembersMeResponse401) & {
  headers: Headers;
};

export type getMembersMeResponse = (getMembersMeResponseSuccess | getMembersMeResponseError)

export const getGetMembersMeUrl = () => {




  return `/api/v1/members/me`
}

export const getMembersMe = async ( options?: RequestInit): Promise<getMembersMeResponse> => {

  return apiClient<getMembersMeResponse>(getGetMembersMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMembersMeQueryKey = () => {
    return [
    `/api/v1/members/me`
    ] as const;
    }


export const getGetMembersMeQueryOptions = <TData = Awaited<ReturnType<typeof getMembersMe>>, TError = GetMembersMe401>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembersMe>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMembersMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMembersMe>>> = ({ signal }) => getMembersMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMembersMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMembersMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMembersMe>>>
export type GetMembersMeQueryError = GetMembersMe401


export function useGetMembersMe<TData = Awaited<ReturnType<typeof getMembersMe>>, TError = GetMembersMe401>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembersMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMembersMe>>,
          TError,
          Awaited<ReturnType<typeof getMembersMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMembersMe<TData = Awaited<ReturnType<typeof getMembersMe>>, TError = GetMembersMe401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembersMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMembersMe>>,
          TError,
          Awaited<ReturnType<typeof getMembersMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMembersMe<TData = Awaited<ReturnType<typeof getMembersMe>>, TError = GetMembersMe401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembersMe>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMembersMe<TData = Awaited<ReturnType<typeof getMembersMe>>, TError = GetMembersMe401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembersMe>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMembersMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Create member from active session if not exists (idempotent)
 */
export type postMembersSyncResponse200 = {
  data: PostMembersSync200
  status: 200
}

export type postMembersSyncResponse201 = {
  data: PostMembersSync201
  status: 201
}

export type postMembersSyncResponse401 = {
  data: PostMembersSync401
  status: 401
}

export type postMembersSyncResponse422 = {
  data: PostMembersSync422
  status: 422
}

export type postMembersSyncResponse500 = {
  data: PostMembersSync500
  status: 500
}

export type postMembersSyncResponseSuccess = (postMembersSyncResponse200 | postMembersSyncResponse201) & {
  headers: Headers;
};
export type postMembersSyncResponseError = (postMembersSyncResponse401 | postMembersSyncResponse422 | postMembersSyncResponse500) & {
  headers: Headers;
};

export type postMembersSyncResponse = (postMembersSyncResponseSuccess | postMembersSyncResponseError)

export const getPostMembersSyncUrl = () => {




  return `/api/v1/members/sync`
}

export const postMembersSync = async ( options?: RequestInit): Promise<postMembersSyncResponse> => {

  return apiClient<postMembersSyncResponse>(getPostMembersSyncUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostMembersSyncMutationOptions = <TError = PostMembersSync401 | PostMembersSync422 | PostMembersSync500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postMembersSync>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postMembersSync>>, TError,void, TContext> => {

const mutationKey = ['postMembersSync'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postMembersSync>>, void> = () => {


          return  postMembersSync(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostMembersSyncMutationResult = NonNullable<Awaited<ReturnType<typeof postMembersSync>>>

    export type PostMembersSyncMutationError = PostMembersSync401 | PostMembersSync422 | PostMembersSync500

    export const usePostMembersSync = <TError = PostMembersSync401 | PostMembersSync422 | PostMembersSync500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postMembersSync>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postMembersSync>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostMembersSyncMutationOptions(options), queryClient);
    }
    /**
 * Link a provider identity to the authenticated member, merging any shadow member
 */
export type postMembersMeIdentitiesResponse201 = {
  data: PostMembersMeIdentities201
  status: 201
}

export type postMembersMeIdentitiesResponse409 = {
  data: PostMembersMeIdentities409
  status: 409
}

export type postMembersMeIdentitiesResponse422 = {
  data: PostMembersMeIdentities422
  status: 422
}

export type postMembersMeIdentitiesResponse500 = {
  data: PostMembersMeIdentities500
  status: 500
}

export type postMembersMeIdentitiesResponseSuccess = (postMembersMeIdentitiesResponse201) & {
  headers: Headers;
};
export type postMembersMeIdentitiesResponseError = (postMembersMeIdentitiesResponse409 | postMembersMeIdentitiesResponse422 | postMembersMeIdentitiesResponse500) & {
  headers: Headers;
};

export type postMembersMeIdentitiesResponse = (postMembersMeIdentitiesResponseSuccess | postMembersMeIdentitiesResponseError)

export const getPostMembersMeIdentitiesUrl = () => {




  return `/api/v1/members/me/identities`
}

export const postMembersMeIdentities = async (postMembersMeIdentitiesBody: PostMembersMeIdentitiesBody, options?: RequestInit): Promise<postMembersMeIdentitiesResponse> => {

  return apiClient<postMembersMeIdentitiesResponse>(getPostMembersMeIdentitiesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postMembersMeIdentitiesBody,)
  }
);}




export const getPostMembersMeIdentitiesMutationOptions = <TError = PostMembersMeIdentities409 | PostMembersMeIdentities422 | PostMembersMeIdentities500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postMembersMeIdentities>>, TError,{data: PostMembersMeIdentitiesBody}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postMembersMeIdentities>>, TError,{data: PostMembersMeIdentitiesBody}, TContext> => {

const mutationKey = ['postMembersMeIdentities'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postMembersMeIdentities>>, {data: PostMembersMeIdentitiesBody}> = (props) => {
          const {data} = props ?? {};

          return  postMembersMeIdentities(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostMembersMeIdentitiesMutationResult = NonNullable<Awaited<ReturnType<typeof postMembersMeIdentities>>>
    export type PostMembersMeIdentitiesMutationBody = PostMembersMeIdentitiesBody
    export type PostMembersMeIdentitiesMutationError = PostMembersMeIdentities409 | PostMembersMeIdentities422 | PostMembersMeIdentities500

    export const usePostMembersMeIdentities = <TError = PostMembersMeIdentities409 | PostMembersMeIdentities422 | PostMembersMeIdentities500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postMembersMeIdentities>>, TError,{data: PostMembersMeIdentitiesBody}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postMembersMeIdentities>>,
        TError,
        {data: PostMembersMeIdentitiesBody},
        TContext
      > => {
      return useMutation(getPostMembersMeIdentitiesMutationOptions(options), queryClient);
    }
    /**
 * List all provider identities linked to the authenticated member
 */
export type getMembersMeIdentitiesResponse200 = {
  data: GetMembersMeIdentities200
  status: 200
}

export type getMembersMeIdentitiesResponseSuccess = (getMembersMeIdentitiesResponse200) & {
  headers: Headers;
};
;

export type getMembersMeIdentitiesResponse = (getMembersMeIdentitiesResponseSuccess)

export const getGetMembersMeIdentitiesUrl = () => {




  return `/api/v1/members/me/identities`
}

export const getMembersMeIdentities = async ( options?: RequestInit): Promise<getMembersMeIdentitiesResponse> => {

  return apiClient<getMembersMeIdentitiesResponse>(getGetMembersMeIdentitiesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMembersMeIdentitiesQueryKey = () => {
    return [
    `/api/v1/members/me/identities`
    ] as const;
    }


export const getGetMembersMeIdentitiesQueryOptions = <TData = Awaited<ReturnType<typeof getMembersMeIdentities>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembersMeIdentities>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMembersMeIdentitiesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMembersMeIdentities>>> = ({ signal }) => getMembersMeIdentities({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMembersMeIdentities>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMembersMeIdentitiesQueryResult = NonNullable<Awaited<ReturnType<typeof getMembersMeIdentities>>>
export type GetMembersMeIdentitiesQueryError = unknown


export function useGetMembersMeIdentities<TData = Awaited<ReturnType<typeof getMembersMeIdentities>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembersMeIdentities>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMembersMeIdentities>>,
          TError,
          Awaited<ReturnType<typeof getMembersMeIdentities>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMembersMeIdentities<TData = Awaited<ReturnType<typeof getMembersMeIdentities>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembersMeIdentities>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMembersMeIdentities>>,
          TError,
          Awaited<ReturnType<typeof getMembersMeIdentities>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMembersMeIdentities<TData = Awaited<ReturnType<typeof getMembersMeIdentities>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembersMeIdentities>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMembersMeIdentities<TData = Awaited<ReturnType<typeof getMembersMeIdentities>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembersMeIdentities>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMembersMeIdentitiesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




