/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Cervo API
 * API for managing bookmarks, workspaces, and members with API key authentication
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteWorkspacesWorkspaceIdIntegrationsIntegrationId403,
  DeleteWorkspacesWorkspaceIdIntegrationsIntegrationId404,
  GetWorkspacesWorkspaceIdIntegrations200,
  GetWorkspacesWorkspaceIdIntegrations403,
  GetWorkspacesWorkspaceIdIntegrations404,
  PostWorkspacesWorkspaceIdIntegrations201,
  PostWorkspacesWorkspaceIdIntegrations403,
  PostWorkspacesWorkspaceIdIntegrations404,
  PostWorkspacesWorkspaceIdIntegrations422,
  PostWorkspacesWorkspaceIdIntegrationsBody
} from '../cervoAPI.schemas';

import { apiClient } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List integrations for a workspace
 */
export type getWorkspacesWorkspaceIdIntegrationsResponse200 = {
  data: GetWorkspacesWorkspaceIdIntegrations200
  status: 200
}

export type getWorkspacesWorkspaceIdIntegrationsResponse403 = {
  data: GetWorkspacesWorkspaceIdIntegrations403
  status: 403
}

export type getWorkspacesWorkspaceIdIntegrationsResponse404 = {
  data: GetWorkspacesWorkspaceIdIntegrations404
  status: 404
}

export type getWorkspacesWorkspaceIdIntegrationsResponseSuccess = (getWorkspacesWorkspaceIdIntegrationsResponse200) & {
  headers: Headers;
};
export type getWorkspacesWorkspaceIdIntegrationsResponseError = (getWorkspacesWorkspaceIdIntegrationsResponse403 | getWorkspacesWorkspaceIdIntegrationsResponse404) & {
  headers: Headers;
};

export type getWorkspacesWorkspaceIdIntegrationsResponse = (getWorkspacesWorkspaceIdIntegrationsResponseSuccess | getWorkspacesWorkspaceIdIntegrationsResponseError)

export const getGetWorkspacesWorkspaceIdIntegrationsUrl = (workspaceId: string,) => {




  return `/api/v1/workspaces/${workspaceId}/integrations`
}

export const getWorkspacesWorkspaceIdIntegrations = async (workspaceId: string, options?: RequestInit): Promise<getWorkspacesWorkspaceIdIntegrationsResponse> => {

  return apiClient<getWorkspacesWorkspaceIdIntegrationsResponse>(getGetWorkspacesWorkspaceIdIntegrationsUrl(workspaceId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetWorkspacesWorkspaceIdIntegrationsQueryKey = (workspaceId: string,) => {
    return [
    `/api/v1/workspaces/${workspaceId}/integrations`
    ] as const;
    }


export const getGetWorkspacesWorkspaceIdIntegrationsQueryOptions = <TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceIdIntegrations>>, TError = GetWorkspacesWorkspaceIdIntegrations403 | GetWorkspacesWorkspaceIdIntegrations404>(workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdIntegrations>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorkspacesWorkspaceIdIntegrationsQueryKey(workspaceId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdIntegrations>>> = ({ signal }) => getWorkspacesWorkspaceIdIntegrations(workspaceId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(workspaceId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdIntegrations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWorkspacesWorkspaceIdIntegrationsQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdIntegrations>>>
export type GetWorkspacesWorkspaceIdIntegrationsQueryError = GetWorkspacesWorkspaceIdIntegrations403 | GetWorkspacesWorkspaceIdIntegrations404


export function useGetWorkspacesWorkspaceIdIntegrations<TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceIdIntegrations>>, TError = GetWorkspacesWorkspaceIdIntegrations403 | GetWorkspacesWorkspaceIdIntegrations404>(
 workspaceId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdIntegrations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspacesWorkspaceIdIntegrations>>,
          TError,
          Awaited<ReturnType<typeof getWorkspacesWorkspaceIdIntegrations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorkspacesWorkspaceIdIntegrations<TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceIdIntegrations>>, TError = GetWorkspacesWorkspaceIdIntegrations403 | GetWorkspacesWorkspaceIdIntegrations404>(
 workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdIntegrations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspacesWorkspaceIdIntegrations>>,
          TError,
          Awaited<ReturnType<typeof getWorkspacesWorkspaceIdIntegrations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorkspacesWorkspaceIdIntegrations<TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceIdIntegrations>>, TError = GetWorkspacesWorkspaceIdIntegrations403 | GetWorkspacesWorkspaceIdIntegrations404>(
 workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdIntegrations>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetWorkspacesWorkspaceIdIntegrations<TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceIdIntegrations>>, TError = GetWorkspacesWorkspaceIdIntegrations403 | GetWorkspacesWorkspaceIdIntegrations404>(
 workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdIntegrations>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWorkspacesWorkspaceIdIntegrationsQueryOptions(workspaceId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Add a platform integration to a workspace
 */
export type postWorkspacesWorkspaceIdIntegrationsResponse201 = {
  data: PostWorkspacesWorkspaceIdIntegrations201
  status: 201
}

export type postWorkspacesWorkspaceIdIntegrationsResponse403 = {
  data: PostWorkspacesWorkspaceIdIntegrations403
  status: 403
}

export type postWorkspacesWorkspaceIdIntegrationsResponse404 = {
  data: PostWorkspacesWorkspaceIdIntegrations404
  status: 404
}

export type postWorkspacesWorkspaceIdIntegrationsResponse422 = {
  data: PostWorkspacesWorkspaceIdIntegrations422
  status: 422
}

export type postWorkspacesWorkspaceIdIntegrationsResponseSuccess = (postWorkspacesWorkspaceIdIntegrationsResponse201) & {
  headers: Headers;
};
export type postWorkspacesWorkspaceIdIntegrationsResponseError = (postWorkspacesWorkspaceIdIntegrationsResponse403 | postWorkspacesWorkspaceIdIntegrationsResponse404 | postWorkspacesWorkspaceIdIntegrationsResponse422) & {
  headers: Headers;
};

export type postWorkspacesWorkspaceIdIntegrationsResponse = (postWorkspacesWorkspaceIdIntegrationsResponseSuccess | postWorkspacesWorkspaceIdIntegrationsResponseError)

export const getPostWorkspacesWorkspaceIdIntegrationsUrl = (workspaceId: string,) => {




  return `/api/v1/workspaces/${workspaceId}/integrations`
}

export const postWorkspacesWorkspaceIdIntegrations = async (workspaceId: string,
    postWorkspacesWorkspaceIdIntegrationsBody: PostWorkspacesWorkspaceIdIntegrationsBody, options?: RequestInit): Promise<postWorkspacesWorkspaceIdIntegrationsResponse> => {

  return apiClient<postWorkspacesWorkspaceIdIntegrationsResponse>(getPostWorkspacesWorkspaceIdIntegrationsUrl(workspaceId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postWorkspacesWorkspaceIdIntegrationsBody,)
  }
);}




export const getPostWorkspacesWorkspaceIdIntegrationsMutationOptions = <TError = PostWorkspacesWorkspaceIdIntegrations403 | PostWorkspacesWorkspaceIdIntegrations404 | PostWorkspacesWorkspaceIdIntegrations422,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWorkspacesWorkspaceIdIntegrations>>, TError,{workspaceId: string;data: PostWorkspacesWorkspaceIdIntegrationsBody}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postWorkspacesWorkspaceIdIntegrations>>, TError,{workspaceId: string;data: PostWorkspacesWorkspaceIdIntegrationsBody}, TContext> => {

const mutationKey = ['postWorkspacesWorkspaceIdIntegrations'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postWorkspacesWorkspaceIdIntegrations>>, {workspaceId: string;data: PostWorkspacesWorkspaceIdIntegrationsBody}> = (props) => {
          const {workspaceId,data} = props ?? {};

          return  postWorkspacesWorkspaceIdIntegrations(workspaceId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostWorkspacesWorkspaceIdIntegrationsMutationResult = NonNullable<Awaited<ReturnType<typeof postWorkspacesWorkspaceIdIntegrations>>>
    export type PostWorkspacesWorkspaceIdIntegrationsMutationBody = PostWorkspacesWorkspaceIdIntegrationsBody
    export type PostWorkspacesWorkspaceIdIntegrationsMutationError = PostWorkspacesWorkspaceIdIntegrations403 | PostWorkspacesWorkspaceIdIntegrations404 | PostWorkspacesWorkspaceIdIntegrations422

    export const usePostWorkspacesWorkspaceIdIntegrations = <TError = PostWorkspacesWorkspaceIdIntegrations403 | PostWorkspacesWorkspaceIdIntegrations404 | PostWorkspacesWorkspaceIdIntegrations422,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWorkspacesWorkspaceIdIntegrations>>, TError,{workspaceId: string;data: PostWorkspacesWorkspaceIdIntegrationsBody}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postWorkspacesWorkspaceIdIntegrations>>,
        TError,
        {workspaceId: string;data: PostWorkspacesWorkspaceIdIntegrationsBody},
        TContext
      > => {
      return useMutation(getPostWorkspacesWorkspaceIdIntegrationsMutationOptions(options), queryClient);
    }
    /**
 * Remove a platform integration from a workspace
 */
export type deleteWorkspacesWorkspaceIdIntegrationsIntegrationIdResponse204 = {
  data: void
  status: 204
}

export type deleteWorkspacesWorkspaceIdIntegrationsIntegrationIdResponse403 = {
  data: DeleteWorkspacesWorkspaceIdIntegrationsIntegrationId403
  status: 403
}

export type deleteWorkspacesWorkspaceIdIntegrationsIntegrationIdResponse404 = {
  data: DeleteWorkspacesWorkspaceIdIntegrationsIntegrationId404
  status: 404
}

export type deleteWorkspacesWorkspaceIdIntegrationsIntegrationIdResponseSuccess = (deleteWorkspacesWorkspaceIdIntegrationsIntegrationIdResponse204) & {
  headers: Headers;
};
export type deleteWorkspacesWorkspaceIdIntegrationsIntegrationIdResponseError = (deleteWorkspacesWorkspaceIdIntegrationsIntegrationIdResponse403 | deleteWorkspacesWorkspaceIdIntegrationsIntegrationIdResponse404) & {
  headers: Headers;
};

export type deleteWorkspacesWorkspaceIdIntegrationsIntegrationIdResponse = (deleteWorkspacesWorkspaceIdIntegrationsIntegrationIdResponseSuccess | deleteWorkspacesWorkspaceIdIntegrationsIntegrationIdResponseError)

export const getDeleteWorkspacesWorkspaceIdIntegrationsIntegrationIdUrl = (workspaceId: string,
    integrationId: string,) => {




  return `/api/v1/workspaces/${workspaceId}/integrations/${integrationId}`
}

export const deleteWorkspacesWorkspaceIdIntegrationsIntegrationId = async (workspaceId: string,
    integrationId: string, options?: RequestInit): Promise<deleteWorkspacesWorkspaceIdIntegrationsIntegrationIdResponse> => {

  return apiClient<deleteWorkspacesWorkspaceIdIntegrationsIntegrationIdResponse>(getDeleteWorkspacesWorkspaceIdIntegrationsIntegrationIdUrl(workspaceId,integrationId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteWorkspacesWorkspaceIdIntegrationsIntegrationIdMutationOptions = <TError = DeleteWorkspacesWorkspaceIdIntegrationsIntegrationId403 | DeleteWorkspacesWorkspaceIdIntegrationsIntegrationId404,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWorkspacesWorkspaceIdIntegrationsIntegrationId>>, TError,{workspaceId: string;integrationId: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteWorkspacesWorkspaceIdIntegrationsIntegrationId>>, TError,{workspaceId: string;integrationId: string}, TContext> => {

const mutationKey = ['deleteWorkspacesWorkspaceIdIntegrationsIntegrationId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteWorkspacesWorkspaceIdIntegrationsIntegrationId>>, {workspaceId: string;integrationId: string}> = (props) => {
          const {workspaceId,integrationId} = props ?? {};

          return  deleteWorkspacesWorkspaceIdIntegrationsIntegrationId(workspaceId,integrationId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteWorkspacesWorkspaceIdIntegrationsIntegrationIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWorkspacesWorkspaceIdIntegrationsIntegrationId>>>

    export type DeleteWorkspacesWorkspaceIdIntegrationsIntegrationIdMutationError = DeleteWorkspacesWorkspaceIdIntegrationsIntegrationId403 | DeleteWorkspacesWorkspaceIdIntegrationsIntegrationId404

    export const useDeleteWorkspacesWorkspaceIdIntegrationsIntegrationId = <TError = DeleteWorkspacesWorkspaceIdIntegrationsIntegrationId403 | DeleteWorkspacesWorkspaceIdIntegrationsIntegrationId404,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWorkspacesWorkspaceIdIntegrationsIntegrationId>>, TError,{workspaceId: string;integrationId: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteWorkspacesWorkspaceIdIntegrationsIntegrationId>>,
        TError,
        {workspaceId: string;integrationId: string},
        TContext
      > => {
      return useMutation(getDeleteWorkspacesWorkspaceIdIntegrationsIntegrationIdMutationOptions(options), queryClient);
    }
