/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Cervo API
 * API for managing bookmarks, workspaces, and members with API key authentication
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import { apiClient } from "../../lib/api-client";
import type {
	GetWorkspacesByIntegration200,
	GetWorkspacesByIntegration404,
	GetWorkspacesByIntegrationParams,
	PostWorkspacesWorkspaceIdIntegrations201,
	PostWorkspacesWorkspaceIdIntegrations404,
	PostWorkspacesWorkspaceIdIntegrations422,
	PostWorkspacesWorkspaceIdIntegrationsBody,
} from "../cervoAPI.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Add a platform integration to a workspace
 */
export type postWorkspacesWorkspaceIdIntegrationsResponse201 = {
	data: PostWorkspacesWorkspaceIdIntegrations201;
	status: 201;
};

export type postWorkspacesWorkspaceIdIntegrationsResponse404 = {
	data: PostWorkspacesWorkspaceIdIntegrations404;
	status: 404;
};

export type postWorkspacesWorkspaceIdIntegrationsResponse422 = {
	data: PostWorkspacesWorkspaceIdIntegrations422;
	status: 422;
};

export type postWorkspacesWorkspaceIdIntegrationsResponseSuccess =
	postWorkspacesWorkspaceIdIntegrationsResponse201 & {
		headers: Headers;
	};
export type postWorkspacesWorkspaceIdIntegrationsResponseError = (
	| postWorkspacesWorkspaceIdIntegrationsResponse404
	| postWorkspacesWorkspaceIdIntegrationsResponse422
) & {
	headers: Headers;
};

export type postWorkspacesWorkspaceIdIntegrationsResponse =
	| postWorkspacesWorkspaceIdIntegrationsResponseSuccess
	| postWorkspacesWorkspaceIdIntegrationsResponseError;

export const getPostWorkspacesWorkspaceIdIntegrationsUrl = (
	workspaceId: string,
) => {
	return `/workspaces/${workspaceId}/integrations`;
};

export const postWorkspacesWorkspaceIdIntegrations = async (
	workspaceId: string,
	postWorkspacesWorkspaceIdIntegrationsBody: PostWorkspacesWorkspaceIdIntegrationsBody,
	options?: RequestInit,
): Promise<postWorkspacesWorkspaceIdIntegrationsResponse> => {
	return apiClient<postWorkspacesWorkspaceIdIntegrationsResponse>(
		getPostWorkspacesWorkspaceIdIntegrationsUrl(workspaceId),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(postWorkspacesWorkspaceIdIntegrationsBody),
		},
	);
};

export const getPostWorkspacesWorkspaceIdIntegrationsMutationOptions = <
	TError =
		| PostWorkspacesWorkspaceIdIntegrations404
		| PostWorkspacesWorkspaceIdIntegrations422,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postWorkspacesWorkspaceIdIntegrations>>,
		TError,
		{ workspaceId: string; data: PostWorkspacesWorkspaceIdIntegrationsBody },
		TContext
	>;
	request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postWorkspacesWorkspaceIdIntegrations>>,
	TError,
	{ workspaceId: string; data: PostWorkspacesWorkspaceIdIntegrationsBody },
	TContext
> => {
	const mutationKey = ["postWorkspacesWorkspaceIdIntegrations"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postWorkspacesWorkspaceIdIntegrations>>,
		{ workspaceId: string; data: PostWorkspacesWorkspaceIdIntegrationsBody }
	> = (props) => {
		const { workspaceId, data } = props ?? {};

		return postWorkspacesWorkspaceIdIntegrations(
			workspaceId,
			data,
			requestOptions,
		);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostWorkspacesWorkspaceIdIntegrationsMutationResult = NonNullable<
	Awaited<ReturnType<typeof postWorkspacesWorkspaceIdIntegrations>>
>;
export type PostWorkspacesWorkspaceIdIntegrationsMutationBody =
	PostWorkspacesWorkspaceIdIntegrationsBody;
export type PostWorkspacesWorkspaceIdIntegrationsMutationError =
	| PostWorkspacesWorkspaceIdIntegrations404
	| PostWorkspacesWorkspaceIdIntegrations422;

export const usePostWorkspacesWorkspaceIdIntegrations = <
	TError =
		| PostWorkspacesWorkspaceIdIntegrations404
		| PostWorkspacesWorkspaceIdIntegrations422,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postWorkspacesWorkspaceIdIntegrations>>,
			TError,
			{ workspaceId: string; data: PostWorkspacesWorkspaceIdIntegrationsBody },
			TContext
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postWorkspacesWorkspaceIdIntegrations>>,
	TError,
	{ workspaceId: string; data: PostWorkspacesWorkspaceIdIntegrationsBody },
	TContext
> => {
	return useMutation(
		getPostWorkspacesWorkspaceIdIntegrationsMutationOptions(options),
		queryClient,
	);
};
/**
 * Find a workspace by its platform integration (bot-facing)
 */
export type getWorkspacesByIntegrationResponse200 = {
	data: GetWorkspacesByIntegration200;
	status: 200;
};

export type getWorkspacesByIntegrationResponse404 = {
	data: GetWorkspacesByIntegration404;
	status: 404;
};

export type getWorkspacesByIntegrationResponseSuccess =
	getWorkspacesByIntegrationResponse200 & {
		headers: Headers;
	};
export type getWorkspacesByIntegrationResponseError =
	getWorkspacesByIntegrationResponse404 & {
		headers: Headers;
	};

export type getWorkspacesByIntegrationResponse =
	| getWorkspacesByIntegrationResponseSuccess
	| getWorkspacesByIntegrationResponseError;

export const getGetWorkspacesByIntegrationUrl = (
	params: GetWorkspacesByIntegrationParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/workspaces/by-integration?${stringifiedParams}`
		: `/workspaces/by-integration`;
};

export const getWorkspacesByIntegration = async (
	params: GetWorkspacesByIntegrationParams,
	options?: RequestInit,
): Promise<getWorkspacesByIntegrationResponse> => {
	return apiClient<getWorkspacesByIntegrationResponse>(
		getGetWorkspacesByIntegrationUrl(params),
		{
			...options,
			method: "GET",
		},
	);
};

export const getGetWorkspacesByIntegrationQueryKey = (
	params?: GetWorkspacesByIntegrationParams,
) => {
	return [`/workspaces/by-integration`, ...(params ? [params] : [])] as const;
};

export const getGetWorkspacesByIntegrationQueryOptions = <
	TData = Awaited<ReturnType<typeof getWorkspacesByIntegration>>,
	TError = GetWorkspacesByIntegration404,
>(
	params: GetWorkspacesByIntegrationParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getWorkspacesByIntegration>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetWorkspacesByIntegrationQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getWorkspacesByIntegration>>
	> = ({ signal }) =>
		getWorkspacesByIntegration(params, { signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getWorkspacesByIntegration>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetWorkspacesByIntegrationQueryResult = NonNullable<
	Awaited<ReturnType<typeof getWorkspacesByIntegration>>
>;
export type GetWorkspacesByIntegrationQueryError =
	GetWorkspacesByIntegration404;

export function useGetWorkspacesByIntegration<
	TData = Awaited<ReturnType<typeof getWorkspacesByIntegration>>,
	TError = GetWorkspacesByIntegration404,
>(
	params: GetWorkspacesByIntegrationParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getWorkspacesByIntegration>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getWorkspacesByIntegration>>,
					TError,
					Awaited<ReturnType<typeof getWorkspacesByIntegration>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWorkspacesByIntegration<
	TData = Awaited<ReturnType<typeof getWorkspacesByIntegration>>,
	TError = GetWorkspacesByIntegration404,
>(
	params: GetWorkspacesByIntegrationParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getWorkspacesByIntegration>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getWorkspacesByIntegration>>,
					TError,
					Awaited<ReturnType<typeof getWorkspacesByIntegration>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWorkspacesByIntegration<
	TData = Awaited<ReturnType<typeof getWorkspacesByIntegration>>,
	TError = GetWorkspacesByIntegration404,
>(
	params: GetWorkspacesByIntegrationParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getWorkspacesByIntegration>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetWorkspacesByIntegration<
	TData = Awaited<ReturnType<typeof getWorkspacesByIntegration>>,
	TError = GetWorkspacesByIntegration404,
>(
	params: GetWorkspacesByIntegrationParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getWorkspacesByIntegration>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetWorkspacesByIntegrationQueryOptions(
		params,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
