/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiResumeChatRouteImport } from './routes/api.resume-chat'
import { Route as AuthWorkspaceRouteImport } from './routes/_auth/workspace'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AppMcpRouteImport } from './routes/_app/mcp'
import { Route as AppLinksRouteImport } from './routes/_app/links'
import { Route as AppComponentsRouteImport } from './routes/_app/components'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppDemoTanstackQueryRouteImport } from './routes/_app/demo/tanstack-query'
import { Route as AppDemoMcpTodosRouteImport } from './routes/_app/demo/mcp-todos'
import { Route as AppDemoBetterAuthRouteImport } from './routes/_app/demo/better-auth'
import { Route as AppDemoApiMcpTodosRouteImport } from './routes/_app/demo/api.mcp-todos'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiResumeChatRoute = ApiResumeChatRouteImport.update({
  id: '/api/resume-chat',
  path: '/api/resume-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWorkspaceRoute = AuthWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AppMcpRoute = AppMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AppRoute,
} as any)
const AppLinksRoute = AppLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AppRoute,
} as any)
const AppComponentsRoute = AppComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDemoTanstackQueryRoute = AppDemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => AppRoute,
} as any)
const AppDemoMcpTodosRoute = AppDemoMcpTodosRouteImport.update({
  id: '/demo/mcp-todos',
  path: '/demo/mcp-todos',
  getParentRoute: () => AppRoute,
} as any)
const AppDemoBetterAuthRoute = AppDemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => AppRoute,
} as any)
const AppDemoApiMcpTodosRoute = AppDemoApiMcpTodosRouteImport.update({
  id: '/demo/api/mcp-todos',
  path: '/demo/api/mcp-todos',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/components': typeof AppComponentsRoute
  '/links': typeof AppLinksRoute
  '/mcp': typeof AppMcpRoute
  '/sign-in': typeof AuthSignInRoute
  '/workspace': typeof AuthWorkspaceRoute
  '/api/resume-chat': typeof ApiResumeChatRoute
  '/demo/better-auth': typeof AppDemoBetterAuthRoute
  '/demo/mcp-todos': typeof AppDemoMcpTodosRoute
  '/demo/tanstack-query': typeof AppDemoTanstackQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/mcp-todos': typeof AppDemoApiMcpTodosRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/components': typeof AppComponentsRoute
  '/links': typeof AppLinksRoute
  '/mcp': typeof AppMcpRoute
  '/sign-in': typeof AuthSignInRoute
  '/workspace': typeof AuthWorkspaceRoute
  '/api/resume-chat': typeof ApiResumeChatRoute
  '/demo/better-auth': typeof AppDemoBetterAuthRoute
  '/demo/mcp-todos': typeof AppDemoMcpTodosRoute
  '/demo/tanstack-query': typeof AppDemoTanstackQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/mcp-todos': typeof AppDemoApiMcpTodosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/components': typeof AppComponentsRoute
  '/_app/links': typeof AppLinksRoute
  '/_app/mcp': typeof AppMcpRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/workspace': typeof AuthWorkspaceRoute
  '/api/resume-chat': typeof ApiResumeChatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/demo/better-auth': typeof AppDemoBetterAuthRoute
  '/_app/demo/mcp-todos': typeof AppDemoMcpTodosRoute
  '/_app/demo/tanstack-query': typeof AppDemoTanstackQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/demo/api/mcp-todos': typeof AppDemoApiMcpTodosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/links'
    | '/mcp'
    | '/sign-in'
    | '/workspace'
    | '/api/resume-chat'
    | '/demo/better-auth'
    | '/demo/mcp-todos'
    | '/demo/tanstack-query'
    | '/api/auth/$'
    | '/demo/api/mcp-todos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components'
    | '/links'
    | '/mcp'
    | '/sign-in'
    | '/workspace'
    | '/api/resume-chat'
    | '/demo/better-auth'
    | '/demo/mcp-todos'
    | '/demo/tanstack-query'
    | '/api/auth/$'
    | '/demo/api/mcp-todos'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/components'
    | '/_app/links'
    | '/_app/mcp'
    | '/_auth/sign-in'
    | '/_auth/workspace'
    | '/api/resume-chat'
    | '/_app/'
    | '/_app/demo/better-auth'
    | '/_app/demo/mcp-todos'
    | '/_app/demo/tanstack-query'
    | '/api/auth/$'
    | '/_app/demo/api/mcp-todos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiResumeChatRoute: typeof ApiResumeChatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/resume-chat': {
      id: '/api/resume-chat'
      path: '/api/resume-chat'
      fullPath: '/api/resume-chat'
      preLoaderRoute: typeof ApiResumeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/workspace': {
      id: '/_auth/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthWorkspaceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/mcp': {
      id: '/_app/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof AppMcpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/links': {
      id: '/_app/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof AppLinksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/components': {
      id: '/_app/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof AppComponentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/demo/tanstack-query': {
      id: '/_app/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof AppDemoTanstackQueryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demo/mcp-todos': {
      id: '/_app/demo/mcp-todos'
      path: '/demo/mcp-todos'
      fullPath: '/demo/mcp-todos'
      preLoaderRoute: typeof AppDemoMcpTodosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demo/better-auth': {
      id: '/_app/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof AppDemoBetterAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demo/api/mcp-todos': {
      id: '/_app/demo/api/mcp-todos'
      path: '/demo/api/mcp-todos'
      fullPath: '/demo/api/mcp-todos'
      preLoaderRoute: typeof AppDemoApiMcpTodosRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppComponentsRoute: typeof AppComponentsRoute
  AppLinksRoute: typeof AppLinksRoute
  AppMcpRoute: typeof AppMcpRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDemoBetterAuthRoute: typeof AppDemoBetterAuthRoute
  AppDemoMcpTodosRoute: typeof AppDemoMcpTodosRoute
  AppDemoTanstackQueryRoute: typeof AppDemoTanstackQueryRoute
  AppDemoApiMcpTodosRoute: typeof AppDemoApiMcpTodosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppComponentsRoute: AppComponentsRoute,
  AppLinksRoute: AppLinksRoute,
  AppMcpRoute: AppMcpRoute,
  AppIndexRoute: AppIndexRoute,
  AppDemoBetterAuthRoute: AppDemoBetterAuthRoute,
  AppDemoMcpTodosRoute: AppDemoMcpTodosRoute,
  AppDemoTanstackQueryRoute: AppDemoTanstackQueryRoute,
  AppDemoApiMcpTodosRoute: AppDemoApiMcpTodosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthWorkspaceRoute: typeof AuthWorkspaceRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthWorkspaceRoute: AuthWorkspaceRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiResumeChatRoute: ApiResumeChatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
