/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiResumeChatRouteImport } from './routes/api.resume-chat'
import { Route as ApiOgRouteImport } from './routes/api.og'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardLinksRouteImport } from './routes/_dashboard/links'
import { Route as DashboardHelpRouteImport } from './routes/_dashboard/help'
import { Route as DashboardAccountRouteImport } from './routes/_dashboard/account'
import { Route as AuthWorkspaceRouteImport } from './routes/_auth/workspace'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AppMcpRouteImport } from './routes/_app/mcp'
import { Route as AppDemoTanstackQueryRouteImport } from './routes/_app/demo/tanstack-query'
import { Route as AppDemoMcpTodosRouteImport } from './routes/_app/demo/mcp-todos'
import { Route as AppDemoBetterAuthRouteImport } from './routes/_app/demo/better-auth'
import { Route as AppDemoApiMcpTodosRouteImport } from './routes/_app/demo/api.mcp-todos'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiResumeChatRoute = ApiResumeChatRouteImport.update({
  id: '/api/resume-chat',
  path: '/api/resume-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLinksRoute = DashboardLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHelpRoute = DashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthWorkspaceRoute = AuthWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AppMcpRoute = AppMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AppRoute,
} as any)
const AppDemoTanstackQueryRoute = AppDemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => AppRoute,
} as any)
const AppDemoMcpTodosRoute = AppDemoMcpTodosRouteImport.update({
  id: '/demo/mcp-todos',
  path: '/demo/mcp-todos',
  getParentRoute: () => AppRoute,
} as any)
const AppDemoBetterAuthRoute = AppDemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => AppRoute,
} as any)
const AppDemoApiMcpTodosRoute = AppDemoApiMcpTodosRouteImport.update({
  id: '/demo/api/mcp-todos',
  path: '/demo/api/mcp-todos',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/mcp': typeof AppMcpRoute
  '/sign-in': typeof AuthSignInRoute
  '/workspace': typeof AuthWorkspaceRoute
  '/account': typeof DashboardAccountRoute
  '/help': typeof DashboardHelpRoute
  '/links': typeof DashboardLinksRoute
  '/settings': typeof DashboardSettingsRoute
  '/api/og': typeof ApiOgRoute
  '/api/resume-chat': typeof ApiResumeChatRoute
  '/demo/better-auth': typeof AppDemoBetterAuthRoute
  '/demo/mcp-todos': typeof AppDemoMcpTodosRoute
  '/demo/tanstack-query': typeof AppDemoTanstackQueryRoute
  '/demo/api/mcp-todos': typeof AppDemoApiMcpTodosRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/mcp': typeof AppMcpRoute
  '/sign-in': typeof AuthSignInRoute
  '/workspace': typeof AuthWorkspaceRoute
  '/account': typeof DashboardAccountRoute
  '/help': typeof DashboardHelpRoute
  '/links': typeof DashboardLinksRoute
  '/settings': typeof DashboardSettingsRoute
  '/api/og': typeof ApiOgRoute
  '/api/resume-chat': typeof ApiResumeChatRoute
  '/demo/better-auth': typeof AppDemoBetterAuthRoute
  '/demo/mcp-todos': typeof AppDemoMcpTodosRoute
  '/demo/tanstack-query': typeof AppDemoTanstackQueryRoute
  '/demo/api/mcp-todos': typeof AppDemoApiMcpTodosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_app/mcp': typeof AppMcpRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/workspace': typeof AuthWorkspaceRoute
  '/_dashboard/account': typeof DashboardAccountRoute
  '/_dashboard/help': typeof DashboardHelpRoute
  '/_dashboard/links': typeof DashboardLinksRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/api/og': typeof ApiOgRoute
  '/api/resume-chat': typeof ApiResumeChatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/demo/better-auth': typeof AppDemoBetterAuthRoute
  '/_app/demo/mcp-todos': typeof AppDemoMcpTodosRoute
  '/_app/demo/tanstack-query': typeof AppDemoTanstackQueryRoute
  '/_app/demo/api/mcp-todos': typeof AppDemoApiMcpTodosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/sign-in'
    | '/workspace'
    | '/account'
    | '/help'
    | '/links'
    | '/settings'
    | '/api/og'
    | '/api/resume-chat'
    | '/demo/better-auth'
    | '/demo/mcp-todos'
    | '/demo/tanstack-query'
    | '/demo/api/mcp-todos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/sign-in'
    | '/workspace'
    | '/account'
    | '/help'
    | '/links'
    | '/settings'
    | '/api/og'
    | '/api/resume-chat'
    | '/demo/better-auth'
    | '/demo/mcp-todos'
    | '/demo/tanstack-query'
    | '/demo/api/mcp-todos'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_dashboard'
    | '/_app/mcp'
    | '/_auth/sign-in'
    | '/_auth/workspace'
    | '/_dashboard/account'
    | '/_dashboard/help'
    | '/_dashboard/links'
    | '/_dashboard/settings'
    | '/api/og'
    | '/api/resume-chat'
    | '/_app/'
    | '/_app/demo/better-auth'
    | '/_app/demo/mcp-todos'
    | '/_app/demo/tanstack-query'
    | '/_app/demo/api/mcp-todos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiOgRoute: typeof ApiOgRoute
  ApiResumeChatRoute: typeof ApiResumeChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/resume-chat': {
      id: '/api/resume-chat'
      path: '/api/resume-chat'
      fullPath: '/api/resume-chat'
      preLoaderRoute: typeof ApiResumeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/links': {
      id: '/_dashboard/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof DashboardLinksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/help': {
      id: '/_dashboard/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof DashboardHelpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/account': {
      id: '/_dashboard/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/workspace': {
      id: '/_auth/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthWorkspaceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/mcp': {
      id: '/_app/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof AppMcpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demo/tanstack-query': {
      id: '/_app/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof AppDemoTanstackQueryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demo/mcp-todos': {
      id: '/_app/demo/mcp-todos'
      path: '/demo/mcp-todos'
      fullPath: '/demo/mcp-todos'
      preLoaderRoute: typeof AppDemoMcpTodosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demo/better-auth': {
      id: '/_app/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof AppDemoBetterAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demo/api/mcp-todos': {
      id: '/_app/demo/api/mcp-todos'
      path: '/demo/api/mcp-todos'
      fullPath: '/demo/api/mcp-todos'
      preLoaderRoute: typeof AppDemoApiMcpTodosRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppMcpRoute: typeof AppMcpRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDemoBetterAuthRoute: typeof AppDemoBetterAuthRoute
  AppDemoMcpTodosRoute: typeof AppDemoMcpTodosRoute
  AppDemoTanstackQueryRoute: typeof AppDemoTanstackQueryRoute
  AppDemoApiMcpTodosRoute: typeof AppDemoApiMcpTodosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMcpRoute: AppMcpRoute,
  AppIndexRoute: AppIndexRoute,
  AppDemoBetterAuthRoute: AppDemoBetterAuthRoute,
  AppDemoMcpTodosRoute: AppDemoMcpTodosRoute,
  AppDemoTanstackQueryRoute: AppDemoTanstackQueryRoute,
  AppDemoApiMcpTodosRoute: AppDemoApiMcpTodosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthWorkspaceRoute: typeof AuthWorkspaceRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthWorkspaceRoute: AuthWorkspaceRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardLinksRoute: typeof DashboardLinksRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardLinksRoute: DashboardLinksRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ApiOgRoute: ApiOgRoute,
  ApiResumeChatRoute: ApiResumeChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
