/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as ApiResumeChatRouteImport } from './routes/api.resume-chat'
import { Route as ApiOgRouteImport } from './routes/api.og'
import { Route as LandingTermsRouteImport } from './routes/_landing/terms'
import { Route as LandingPrivacyRouteImport } from './routes/_landing/privacy'
import { Route as LandingPricingRouteImport } from './routes/_landing/pricing'
import { Route as LandingFaqRouteImport } from './routes/_landing/faq'
import { Route as LandingDiscordRouteImport } from './routes/_landing/discord'
import { Route as LandingChangelogRouteImport } from './routes/_landing/changelog'
import { Route as LandingBlogRouteImport } from './routes/_landing/blog'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardLinksRouteImport } from './routes/_dashboard/links'
import { Route as DashboardHelpRouteImport } from './routes/_dashboard/help'
import { Route as DashboardAccountRouteImport } from './routes/_dashboard/account'
import { Route as AuthWorkspaceRouteImport } from './routes/_auth/workspace'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthCallbackRouteImport } from './routes/_auth/callback'
import { Route as AppMcpRouteImport } from './routes/_app/mcp'
import { Route as AppDemoTanstackQueryRouteImport } from './routes/_app/demo/tanstack-query'
import { Route as AppDemoMcpTodosRouteImport } from './routes/_app/demo/mcp-todos'
import { Route as AppDemoBetterAuthRouteImport } from './routes/_app/demo/better-auth'
import { Route as AppDemoApiMcpTodosRouteImport } from './routes/_app/demo/api.mcp-todos'

const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const ApiResumeChatRoute = ApiResumeChatRouteImport.update({
  id: '/api/resume-chat',
  path: '/api/resume-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingTermsRoute = LandingTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LandingRoute,
} as any)
const LandingPrivacyRoute = LandingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LandingRoute,
} as any)
const LandingPricingRoute = LandingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => LandingRoute,
} as any)
const LandingFaqRoute = LandingFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LandingRoute,
} as any)
const LandingDiscordRoute = LandingDiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => LandingRoute,
} as any)
const LandingChangelogRoute = LandingChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => LandingRoute,
} as any)
const LandingBlogRoute = LandingBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => LandingRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLinksRoute = DashboardLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHelpRoute = DashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthWorkspaceRoute = AuthWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AppMcpRoute = AppMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AppRoute,
} as any)
const AppDemoTanstackQueryRoute = AppDemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => AppRoute,
} as any)
const AppDemoMcpTodosRoute = AppDemoMcpTodosRouteImport.update({
  id: '/demo/mcp-todos',
  path: '/demo/mcp-todos',
  getParentRoute: () => AppRoute,
} as any)
const AppDemoBetterAuthRoute = AppDemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => AppRoute,
} as any)
const AppDemoApiMcpTodosRoute = AppDemoApiMcpTodosRouteImport.update({
  id: '/demo/api/mcp-todos',
  path: '/demo/api/mcp-todos',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingIndexRoute
  '/mcp': typeof AppMcpRoute
  '/callback': typeof AuthCallbackRoute
  '/sign-in': typeof AuthSignInRoute
  '/workspace': typeof AuthWorkspaceRoute
  '/account': typeof DashboardAccountRoute
  '/help': typeof DashboardHelpRoute
  '/links': typeof DashboardLinksRoute
  '/settings': typeof DashboardSettingsRoute
  '/blog': typeof LandingBlogRoute
  '/changelog': typeof LandingChangelogRoute
  '/discord': typeof LandingDiscordRoute
  '/faq': typeof LandingFaqRoute
  '/pricing': typeof LandingPricingRoute
  '/privacy': typeof LandingPrivacyRoute
  '/terms': typeof LandingTermsRoute
  '/api/og': typeof ApiOgRoute
  '/api/resume-chat': typeof ApiResumeChatRoute
  '/demo/better-auth': typeof AppDemoBetterAuthRoute
  '/demo/mcp-todos': typeof AppDemoMcpTodosRoute
  '/demo/tanstack-query': typeof AppDemoTanstackQueryRoute
  '/demo/api/mcp-todos': typeof AppDemoApiMcpTodosRoute
}
export interface FileRoutesByTo {
  '/': typeof LandingIndexRoute
  '/mcp': typeof AppMcpRoute
  '/callback': typeof AuthCallbackRoute
  '/sign-in': typeof AuthSignInRoute
  '/workspace': typeof AuthWorkspaceRoute
  '/account': typeof DashboardAccountRoute
  '/help': typeof DashboardHelpRoute
  '/links': typeof DashboardLinksRoute
  '/settings': typeof DashboardSettingsRoute
  '/blog': typeof LandingBlogRoute
  '/changelog': typeof LandingChangelogRoute
  '/discord': typeof LandingDiscordRoute
  '/faq': typeof LandingFaqRoute
  '/pricing': typeof LandingPricingRoute
  '/privacy': typeof LandingPrivacyRoute
  '/terms': typeof LandingTermsRoute
  '/api/og': typeof ApiOgRoute
  '/api/resume-chat': typeof ApiResumeChatRoute
  '/demo/better-auth': typeof AppDemoBetterAuthRoute
  '/demo/mcp-todos': typeof AppDemoMcpTodosRoute
  '/demo/tanstack-query': typeof AppDemoTanstackQueryRoute
  '/demo/api/mcp-todos': typeof AppDemoApiMcpTodosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_landing': typeof LandingRouteWithChildren
  '/_app/mcp': typeof AppMcpRoute
  '/_auth/callback': typeof AuthCallbackRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/workspace': typeof AuthWorkspaceRoute
  '/_dashboard/account': typeof DashboardAccountRoute
  '/_dashboard/help': typeof DashboardHelpRoute
  '/_dashboard/links': typeof DashboardLinksRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_landing/blog': typeof LandingBlogRoute
  '/_landing/changelog': typeof LandingChangelogRoute
  '/_landing/discord': typeof LandingDiscordRoute
  '/_landing/faq': typeof LandingFaqRoute
  '/_landing/pricing': typeof LandingPricingRoute
  '/_landing/privacy': typeof LandingPrivacyRoute
  '/_landing/terms': typeof LandingTermsRoute
  '/api/og': typeof ApiOgRoute
  '/api/resume-chat': typeof ApiResumeChatRoute
  '/_landing/': typeof LandingIndexRoute
  '/_app/demo/better-auth': typeof AppDemoBetterAuthRoute
  '/_app/demo/mcp-todos': typeof AppDemoMcpTodosRoute
  '/_app/demo/tanstack-query': typeof AppDemoTanstackQueryRoute
  '/_app/demo/api/mcp-todos': typeof AppDemoApiMcpTodosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/callback'
    | '/sign-in'
    | '/workspace'
    | '/account'
    | '/help'
    | '/links'
    | '/settings'
    | '/blog'
    | '/changelog'
    | '/discord'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/api/og'
    | '/api/resume-chat'
    | '/demo/better-auth'
    | '/demo/mcp-todos'
    | '/demo/tanstack-query'
    | '/demo/api/mcp-todos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/callback'
    | '/sign-in'
    | '/workspace'
    | '/account'
    | '/help'
    | '/links'
    | '/settings'
    | '/blog'
    | '/changelog'
    | '/discord'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/api/og'
    | '/api/resume-chat'
    | '/demo/better-auth'
    | '/demo/mcp-todos'
    | '/demo/tanstack-query'
    | '/demo/api/mcp-todos'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_dashboard'
    | '/_landing'
    | '/_app/mcp'
    | '/_auth/callback'
    | '/_auth/sign-in'
    | '/_auth/workspace'
    | '/_dashboard/account'
    | '/_dashboard/help'
    | '/_dashboard/links'
    | '/_dashboard/settings'
    | '/_landing/blog'
    | '/_landing/changelog'
    | '/_landing/discord'
    | '/_landing/faq'
    | '/_landing/pricing'
    | '/_landing/privacy'
    | '/_landing/terms'
    | '/api/og'
    | '/api/resume-chat'
    | '/_landing/'
    | '/_app/demo/better-auth'
    | '/_app/demo/mcp-todos'
    | '/_app/demo/tanstack-query'
    | '/_app/demo/api/mcp-todos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LandingRoute: typeof LandingRouteWithChildren
  ApiOgRoute: typeof ApiOgRoute
  ApiResumeChatRoute: typeof ApiResumeChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/api/resume-chat': {
      id: '/api/resume-chat'
      path: '/api/resume-chat'
      fullPath: '/api/resume-chat'
      preLoaderRoute: typeof ApiResumeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/terms': {
      id: '/_landing/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof LandingTermsRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/privacy': {
      id: '/_landing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof LandingPrivacyRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/pricing': {
      id: '/_landing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof LandingPricingRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/faq': {
      id: '/_landing/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof LandingFaqRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/discord': {
      id: '/_landing/discord'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof LandingDiscordRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/changelog': {
      id: '/_landing/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof LandingChangelogRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/blog': {
      id: '/_landing/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof LandingBlogRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/links': {
      id: '/_dashboard/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof DashboardLinksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/help': {
      id: '/_dashboard/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof DashboardHelpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/account': {
      id: '/_dashboard/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/workspace': {
      id: '/_auth/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthWorkspaceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/callback': {
      id: '/_auth/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/mcp': {
      id: '/_app/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof AppMcpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demo/tanstack-query': {
      id: '/_app/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof AppDemoTanstackQueryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demo/mcp-todos': {
      id: '/_app/demo/mcp-todos'
      path: '/demo/mcp-todos'
      fullPath: '/demo/mcp-todos'
      preLoaderRoute: typeof AppDemoMcpTodosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demo/better-auth': {
      id: '/_app/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof AppDemoBetterAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demo/api/mcp-todos': {
      id: '/_app/demo/api/mcp-todos'
      path: '/demo/api/mcp-todos'
      fullPath: '/demo/api/mcp-todos'
      preLoaderRoute: typeof AppDemoApiMcpTodosRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppMcpRoute: typeof AppMcpRoute
  AppDemoBetterAuthRoute: typeof AppDemoBetterAuthRoute
  AppDemoMcpTodosRoute: typeof AppDemoMcpTodosRoute
  AppDemoTanstackQueryRoute: typeof AppDemoTanstackQueryRoute
  AppDemoApiMcpTodosRoute: typeof AppDemoApiMcpTodosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMcpRoute: AppMcpRoute,
  AppDemoBetterAuthRoute: AppDemoBetterAuthRoute,
  AppDemoMcpTodosRoute: AppDemoMcpTodosRoute,
  AppDemoTanstackQueryRoute: AppDemoTanstackQueryRoute,
  AppDemoApiMcpTodosRoute: AppDemoApiMcpTodosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthWorkspaceRoute: typeof AuthWorkspaceRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthWorkspaceRoute: AuthWorkspaceRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardLinksRoute: typeof DashboardLinksRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardLinksRoute: DashboardLinksRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface LandingRouteChildren {
  LandingBlogRoute: typeof LandingBlogRoute
  LandingChangelogRoute: typeof LandingChangelogRoute
  LandingDiscordRoute: typeof LandingDiscordRoute
  LandingFaqRoute: typeof LandingFaqRoute
  LandingPricingRoute: typeof LandingPricingRoute
  LandingPrivacyRoute: typeof LandingPrivacyRoute
  LandingTermsRoute: typeof LandingTermsRoute
  LandingIndexRoute: typeof LandingIndexRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingBlogRoute: LandingBlogRoute,
  LandingChangelogRoute: LandingChangelogRoute,
  LandingDiscordRoute: LandingDiscordRoute,
  LandingFaqRoute: LandingFaqRoute,
  LandingPricingRoute: LandingPricingRoute,
  LandingPrivacyRoute: LandingPrivacyRoute,
  LandingTermsRoute: LandingTermsRoute,
  LandingIndexRoute: LandingIndexRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LandingRoute: LandingRouteWithChildren,
  ApiOgRoute: ApiOgRoute,
  ApiResumeChatRoute: ApiResumeChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
